### ISSUE TITLE
Submission for 24h youtube stream

### ISSUE THREAD

**Issue by noisycomputer** [maxence-charriere/lofimusic#1]
Hi @maxence-charriere 
I've recently started curating a 24hr live stream on youtube with cool stuff from various lofi discords, soundcloud, and submissions. I've worked out the stability issues(aside from unplanned ISP outages lol) and automated the restart so its mostly hands off at this point other than updating the playlist. Check out the stream and let me know if you think it would be a good fit.

Crates.fm - lo fi, hiphop, golden era, boombap radio
https://crates.fm
https://crates.fm/live
https://instagram.com/cratesfm

Youtube live link: https://www.youtube.com/channel/UCDapiw3iGKB1Boi-e2ka6aw/live
Email:contact@crates.fm

Thanks for making cool contributions to the community.

**Comment by maxence-charriere** [comment]
Hello @noisycomputer,
I try to add it but look like the live stream does not work when embbedded:

<img width="1718" alt="Screen Shot 2020-09-14 at 8 45 32 PM" src="https://user-images.githubusercontent.com/2692731/93125330-4551bc80-f6cb-11ea-8707-ede816ea39ac.png">

Maybe the other chan have set some options that you did not.
Here is the code I used:

```go
		{
			Name: "Crates.fm ",
			ID:   "KJ2CzjWPI8Q",
			Slug: "cratesfm",
			SocialMedia: []link{
				{
					URL:       "https://youtu.be/KJ2CzjWPI8Q",
					MediaSlug: "youtube",
				},
				{
					URL:       "https://www.instagram.com/cratesfm/",
					MediaSlug: "instagram",
				},
				{
					URL:       "https://crates.fm",
					MediaSlug: "web",
				},
			},
		},
```
I got the video ID from the share button on your Youtube Channel.

**Comment by noisycomputer** [comment]
Ah yea, I forgot youtube actually restricts embed >1000 subscribers. Thanks for trying! I''l reopen once I'm eligible for embeds.

**Comment by noisycomputer** [comment]
Also just an infrastructure FYI, those ID's change if the stream restarts for any reason. The channelID/live is static.
