### ISSUE TITLE
Stop/Pause button or key

### ISSUE THREAD

**Issue by pelly-ryu** [maxence-charriere/lofimusic#13]
as far as i know, once i start the radio, i can stop/pause it only when i quit it

How about adding a feature that makes radios stop or pause?

If adding new button or ui component is hard, maybe a shortcut like spacebar would be great, i think.
(like youtube's)

**Comment by pelly-ryu** [comment]
#5 
I've found this issue
it seems that pause button wasn't added but mute was.

**Comment by cryptrz** [comment]
On which web browser do you use it ? Is is a Chromium-based ? On Firefox, the play/pause button is at the bottom left, on the Github and Twitter links.

**Comment by pelly-ryu** [comment]
> On which web browser do you use it ? Is is a Chromium-based ? On Firefox, the play/pause button is at the bottom left, on the Github and Twitter links.

![Screen Shot 2020-12-22 at 1 13 22 AM](https://user-images.githubusercontent.com/6833226/102797328-82280080-43ea-11eb-89fa-d93c7679fc80.png)

You mean this one? This one is the play button but no pause. Additionally, it should be center actually. like below:

![Screen Shot 2020-12-22 at 1 14 09 AM](https://user-images.githubusercontent.com/6833226/102797411-9ff56580-43ea-11eb-8371-633f5f41a8e8.png)
(chrome)

**Comment by cryptrz** [comment]
Yes, this is exactly what I have on Firefox, button on the left. 
![image](https://user-images.githubusercontent.com/68272257/102932661-62a3dd00-44a9-11eb-8f6a-d379e3f619a7.png)


It's centered on Brave (Chromium-based).
![image](https://user-images.githubusercontent.com/68272257/102932724-7a7b6100-44a9-11eb-8bf7-e2fbc910cc3b.png)

CSS compatibilities are totally opposed between Firefox and Chrome, it's not always easy to have a similar display between the two (it reminds the IE era)

![image](https://user-images.githubusercontent.com/68272257/102933039-202ed000-44aa-11eb-88cb-f06aa8aca736.png)
source : [https://caniuse.com/?compare=firefox+86,chrome+90&compareCats=all](url)

**Comment by maxence-charriere** [comment]
Just pushed an update that fixes it on firefox.

**Comment by notiv-nt** [comment]
Well, where is the pause button?

**Comment by cryptrz** [comment]
F5

**Comment by AaronPorts** [comment]
Still missing the play/pause button.

**Comment by maxence-charriere** [comment]
Implemented it yesterday, come back next week when i release new version :)

**Comment by maxence-charriere** [comment]
A little tease here:
<img width="1762" alt="Screen Shot 2021-04-09 at 4 29 32 AM" src="https://user-images.githubusercontent.com/2692731/114092550-97b72c80-98ec-11eb-8215-2860226e7c7d.png">

**Comment by notiv-nt** [comment]
@maxence-charriere it should be at center of the screen

**Comment by maxence-charriere** [comment]
Not it is where it is meant to be :)
