### ISSUE TITLE
Station request: Please add lofi code beats

### ISSUE THREAD

**Issue by michaelbdavidson7** [maxence-charriere/lofimusic#14]
Hi there,
Please add this station https://www.youtube.com/watch?v=bmVKaAV_7-A 
You are awesome! Thank you!

**Comment by maxence-charriere** [comment]
Hello,
Thanks for the kind words. Just added your station. I like the animation :).

**Comment by michaelbdavidson7** [comment]
Woo! you are awesome! Thanks!
