### ISSUE TITLE
Scrollbars on Firefox

### ISSUE THREAD

**Issue by oscarbailey-tc** [maxence-charriere/lofimusic#17]
I'm getting scrollbars appearing on Firefox:

![scrollbars_2](https://user-images.githubusercontent.com/79094698/114531309-b185a600-9c43-11eb-9928-e84316f55681.png)

Let me know if you need more info

**Comment by maxence-charriere** [comment]
What is the OS and firefox version?

**Comment by oscarbailey-tc** [comment]
No problem - OS is Windows, Firefox version is 87.0

**Comment by maxence-charriere** [comment]
Just fixed it, thank you so much for this :)
