### ISSUE TITLE
Some lives are moved

### ISSUE THREAD

**Issue by kawarimidoll** [maxence-charriere/lofimusic#18]
"STAR WARS - AHSOKA TANO" and "THE JAZZ HOP CAFÉ" are unavailable from lofimusic.app, the URLs seems to be old.

"STAR WARS - AHSOKA TANO" moved to here: https://www.youtube.com/watch?v=o33l32ZrIy8
"THE JAZZ HOP CAFÉ" moved to here: https://www.youtube.com/watch?v=vNSPGHo8HVc

**Comment by maxence-charriere** [comment]
I updated the app this weekend. You must run the old version. Just reload the page and you should see the new one.
`Ashoka` has been renamed `Starwars Sunday`. For Jazzhop I removed it since it was performed not very well according to my analytics. I can put it back if you really like it.

**Comment by maxence-charriere** [comment]
<img width="640" alt="Screen Shot 2021-04-09 at 7 23 30 PM" src="https://user-images.githubusercontent.com/2692731/114543098-57103800-9c8b-11eb-9757-c1c86fdc6c75.png">

**Comment by kawarimidoll** [comment]
Sorry...as you say, I looked at old version.
Thanks for your quick reply!
