### ISSUE TITLE
Submission for more Radios

### ISSUE THREAD

**Issue by SentinelWinter** [maxence-charriere/lofimusic#2]
I saw the post you made on reddit and jump onboard as fast as possible, I wanted to submit a few more 24/7 stations since these are the one's I usually frequent late at night when i'm doing work. 
1. https://www.youtube.com/watch?v=US6iyJKGNLI 
2. https://www.youtube.com/watch?v=pH3xU1YcjaA 
3. https://www.youtube.com/watch?v=l7TxwBhtTUY
They're not exactly mainstream but two of them have been around almost as long as the study girl.

**Comment by QuintenGates** [comment]
As there's only one issue open right now I'd gathered I'd just put this here as another request:

https://www.youtube.com/watch?v=bjZ_O1gWlx4
