### ISSUE TITLE
New and Returning Stations 

### ISSUE THREAD

**Issue by SentinelWinter** [maxence-charriere/lofimusic#31]
Hello Maxence
I've been actively using your amazing app since I saw that post on reddit back in 2020. It's been a long while but it's really helped with organization and during my long work nights thanks to college. 

I wanted to ask if the following stations could be added 

MonstaFluff's Space Voyage- https://www.youtube.com/watch?v=zVqJv_dKUEs
and 
Steezy's Junk Fluff- https://www.youtube.com/watch?v=xgirCNccI68
Junk Fluff used to be on the app but the link was deactivated when it had suddenly shutdown, this new, active link should work. 

Both of these are long running stations that I think would be great additions to the app's current roster of stations. Again, thanks for this app, it's helped me more than I can say here.

**Comment by maxence-charriere** [comment]
Hey, thanks for the kind words. I ll add them back when i get a moment :)

**Comment by maxence-charriere** [comment]
I put back the space girl.
Sadly, the Junky Fluff video is blocked for embedded players.

**Comment by SentinelWinter** [comment]
Ah, that's unfortunate, thanks anyway!
