### ISSUE TITLE
Bootleg Smoke station broken

### ISSUE THREAD

**Issue by alienator88** [maxence-charriere/lofimusic#32]
Seeing the following error on the bootleg smoke station:

youtube player error:
    code:        150
    description: video cannot be played in embedded players

**Comment by kazumi513** [comment]
Same with CollegeLonely station. Recommendations you could swap these errored stations with: 

https://www.youtube.com/watch?v=-9gEgshJUuY
https://www.youtube.com/watch?v=HDhR2Yhnvfo
https://www.youtube.com/watch?v=Qt0-9mO-ZXY
https://www.youtube.com/watch?v=ORBwkXsUNEs

**Comment by alienator88** [comment]
CollegeLonely seems to work for me still. Those are some nice suggestions man, I'm going to add these to my playlist :)

**Comment by kazumi513** [comment]
Also this one too: https://www.youtube.com/watch?v=XDh0JcxrbPM

**Comment by alienator88** [comment]
That's the same as this one haha: https://lofimusic.app/collegemusic-guy

**Comment by stuartskelton** [comment]
I have updated the college guy link in a PR.
