### ISSUE TITLE
Add Firefox support

### ISSUE THREAD

**Issue by deroverda** [maxence-charriere/lofimusic#34]
Hi, 

Could you please start supporting Firefox?

**Comment by maxence-charriere** [comment]
It is supported on my setup:

![Screen Shot 2022-05-23 at 3 48 23 PM](https://user-images.githubusercontent.com/2692731/169834001-ce523e64-2789-44ef-aded-88ca2c6c9a3a.png)

**Comment by deroverda** [comment]
> It is supported on my setup:
> 
> ![Screen Shot 2022-05-23 at 3 48 23 PM](https://user-images.githubusercontent.com/2692731/169834001-ce523e64-2789-44ef-aded-88ca2c6c9a3a.png)

Ok, weird. Must be related to some privacy settings in uBlock or Firefox that I've added. Thanks for confirming that it works.
