### ISSUE TITLE
Add a pause/mute button

### ISSUE THREAD

**Issue by VaysseRobin** [maxence-charriere/lofimusic#5]
Hi, it's a really nice project !
It would be cool to have a mute button in the application for when we want to cut the music for a while.
Thanks

**Comment by VaysseRobin** [comment]
Oups, I did not see that a Pull request have been made for this feature (also another issue have been created in the same time). I close this issue.

**Comment by X-Ryl669** [comment]
I don't think it's the same issue. A pause button is missing, IMHO.

**Comment by drandreaskrueger** [comment]
Yes, I miss it too.  I can mute it, but then probably there will still be traffic, right?

What you could do is abuse "mute" for "pause" too = zero the volume, make the wobbling of the video freeze, stop the stream.

**Comment by jmiskovic** [comment]
I can confirm there's still network traffic when volume is muted. Please re-open this ticket to track the pausing feature.
